
###

GET http://localhost:3000/post

###

GET http://localhost:3000/post?sender=leah

###
GET http://localhost:3000/post/6228ae4634a0b06d12c49430

###

POST http://localhost:3000/post
Content-Type: application/json

{
    "message": "this is my new message",
    "sender": "leah" 
}

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "th@t.com",
    "password": "222222" 
}


###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email" : "t2t@t.com",
    "password" : "2282222"
}



###
DELETE  http://localhost:3000/post
